# Fonts & Ligatures
font_family      CaskaydiaCove Nerd Font
font_size        8.9

# Window Padding & Opacity
background_opacity 0.90

# Kitty uses single values for padding
# To mimic your 15,0 and 10,0 Ghostty setup:
window_padding_width 10 0 10 15
# (Format: top right bottom left)

# Colors (Catppuccin Mocha essentials)
foreground            #CDD6F4
background            #242124
selection_background  #F5E0DC
selection_foreground  #1E1E2E
cursor                #F5E0DC
cursor_text_color     #1E1E2E

# Palette
color0  #43465A
color8  #43465A

color1  #f4403e
color9  #f4403e

color2  #A6E3A1
color10 #A6E3A1

color3  #F9E2AF
color11 #F9E2AF

color4  #87B0F9
color12 #87B0F9

color5  #a53ef2
color13 #a53ef2

color6  #94E2D5
color14 #94E2D5

color7  #CDD6F4
color15 #A1A8C9

# Behavior & Decorations
shell zsh
hide_window_decorations yes
confirm_os_window_close 0

# Note: Kitty does not support custom-shader for cursor tails natively.
